### ISSUE TITLE
dropout rate for main results

### ISSUE THREAD

**Issue by initial-h** [TakuyaHiraoka/Dropout-Q-Functions-for-Doubly-Efficient-Reinforcement-Learning#1]
Hi, 

Thanks for this interesting work. I find Table 8 lists a dropout rate 0.01, but Table 9 lists some other values. I'm wondering which parameter is used for the main results in the paper. 

Besides, if I run the algorithm for other tasks, is 0.01 a good value, or do you have some recommended values that I need to seach for this parameter?

Thanks!

**Comment by TakuyaHiraoka** [comment]
Hi, 
Thank you for your question. 

> I find Table 8 lists a dropout rate 0.01, but Table 9 lists some other values. I'm wondering which parameter is used for the main results in the paper. 

The dropout rate 0.01 is used for the main results in the paper.  
Values listed in Table 9 are used for supplemental results (Figures 14--20). 

> Besides, if I run the algorithm for other tasks, is 0.01 a good value, or do you have some recommended values that I need to search for this parameter?

I recommend searching best dropout rate value among { 0.1, 0.01, 0.0 (i.e., no dropout) }.
