### ISSUE TITLE
Calculation of next_q

### ISSUE THREAD

**Issue by beardyFace** [TakuyaHiraoka/Dropout-Q-Functions-for-Doubly-Efficient-Reinforcement-Learning#2]
The calculation for the target_q for RedQ and sac appears to be wrong unless there is a negation somewhere else that accounts for this, which I can't see. 

```
def calc_target_q(self, states, actions, rewards, next_states, dones):
        ...
            if self.method == "sac" or self.method == "redq":
                next_q = torch.min(next_q1, next_q2) + self.alpha * next_entropies
        ...
        target_q = (rewards / (self.multi_step * 1.0)) + (1.0 - dones) * self.gamma_n * next_q
        return target_q
```

Should this not be negative alpha - ```next_q = torch.min(next_q1, next_q2) - self.alpha * next_entropies```?

**Comment by TakuyaHiraoka** [comment]
@beardyFace 

Hi, thank you for pointing this out!

> The calculation for the target_q for RedQ and SAC appears to be wrong unless there is a negation somewhere else that accounts for this, which I can't see.

There is a negation in the calculation of `next_entropies`:

https://github.com/TakuyaHiraoka/Dropout-Q-Functions-for-Doubly-Efficient-Reinforcement-Learning/blob/f89a79ac72e9c218d440f7dbcff1d9fed87702df/KUCodebase/code/model.py#L130

**Comment by beardyFace** [comment]
Ah! Missed that, one obvious place I didn't check. 

Our replication of DroQ has also since reproduced similar results.
